### ISSUE TITLE
Sort order folder and files

### ISSUE THREAD

**Issue by tanrak** [joedf/stahky#10]
Hi, nice little helper. It would be nice if the folders came first and then the files when sorting.
Edit: Maybe as option setting in stahky.ini?

**Comment by joedf** [comment]
Good idea, currently it simply does everything alphabetically. 👍 
I'll add an option to `SortFoldersFirst` or something like that.

**Comment by joedf** [comment]
v0.1.0.8 now available! 🚀 

Make you sure you have `SortFoldersFirst=1` in your `stahky.ini` file to enable this.

**Comment by tanrak** [comment]
This was fast! Thanks, it works as expected.

**Comment by joedf** [comment]
Awesome, great to hear. 👍
