### ISSUE TITLE
Some lnk shortcut files are broken

### ISSUE THREAD

**Issue by joedf** [joedf/stahky#2]
[Vivaldi.lnk.txt](https://github.com/joedf/stahky/files/4914388/Vivaldi.lnk.txt)

**Comment by joedf** [comment]
![image](https://user-images.githubusercontent.com/3848219/87339599-db733600-c514-11ea-96c1-3a1b846e2ae9.png)

**Comment by joedf** [comment]
Possibly fixed.

Edit: Nope. Occurs in specifically in compiled form with ahk unicode 32bit, not script form or 64 bit.

**Comment by hi5** [comment]
Just a thought: Quote the path(s) in the FileCreateShort command? See "%A_ScriptFullPath%" in example 1 https://www.autohotkey.com/docs/commands/FileCreateShortcut.htm#ExBasic ?

**Comment by joedf** [comment]
I'm not sure what's going on. I have quotes here, it just seems 32bit is buggy with this one specific shortcut I have (Vivaldi.lnk).
It's not a shortcut I've made myself.
https://github.com/joedf/stahky/blob/71503613f4ce66ffa50201b8483660cb7228ac6d/lib/utils.ahk#L80

I think this might be related to "shell execute" v.s. "running"...

**Comment by joedf** [comment]
I think I've found the culprit. I think shortcut makes use of the system variable which is either "Program files (x86)" or "Program files" for 64bit. Since Vivaldi is actually located in the later and not the former, the run command fails.

**Comment by joedf** [comment]
Working now!

**Comment by hi5** [comment]
Would try/catch be useful to add?
```
Try
   Run ...
Catch
   MsgBox Stahky can't Run :)
```

**Comment by joedf** [comment]
Agreed ahaha! I went overboard and added 2 ErrorLevel checks and a try-catch 😅 ...
.... but I missed the smiley :(
