### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by innuendo33** [joedf/stahky#9]
Hi 

Compared to previous versions of your app , I can't create any shortcut when drag and drop folders on exe. 

The only menu I have is the content of stahky folder I copied on main disk 

I got message as it success but there is no shortcuts at all following the path message confirmation .
Running windows 10 version 20h1 ( 19041.292 ) 64 bits 
So I stick with old versions 

EDIT: wow , got it to work by copying stahky.exe and stahky.ini in the target folder to display the menu of its content. 
Not practical if I have to copy each time those files in target folders ... :/

**Comment by joedf** [comment]
Hi there!
You have to drag a folder onto stahky. The shortcut is then create in the same parent folder as that folder.
Simply launching Stahky will make it show a menu for it's current working directory.

What are the file locations of everything you tried before moving stahky.exe itself?
Also which version of stahky? v0.1.0.1 x64?

Perhaps by default, the shortcut should appear in the same folder as stahky itself? What do you think it better?

**Comment by innuendo33** [comment]
Hi Joe ! and thanks for help :) 
I finally made it work ( didn't know how I failed before ) 
2 notes though : 

- The shortcut after dra drop folder on exe appear in Stahky folder already ( and yes I think it's ok like that , every shortcut in same place for better management instead of browsing at root folders themselves ) 

- I'm used to have my taskbar on top position and when clic on pinned stahky shortcut , menu popups at bottom 
Is there any setting in ini to add or edit to get it right under taskbar shortcut icon ?

**Comment by joedf** [comment]
@innuendo33 Thanks for the feedback!
I've implemented automatic positioning relative to the taskbar: https://github.com/joedf/stahky/commit/354f7c2276e2a2bf16c529e91900028ba7bae5aa
Pushing version 0.1.0.7 soon.

**Comment by joedf** [comment]
https://github.com/joedf/stahky/releases/tag/v0.1.0.7

**Comment by innuendo33** [comment]
Hi Joe ! 
Thank you for hard work , much appreciated ! 
Now displays fine with top taskbar :)

I have another request if you don't mind I would ask in MP , how can I join you ( mail betteer for me ) to submit a question as you are an AHK user and didn't got any help on official forums :/ 

Regards

**Comment by joedf** [comment]
Sure, no worries. I'll consider this case closed then. 👍 

You can email me or send me a pm on the forums. I best like to share the solutions; you can simply @ mention me in your forum thread. Or you can also send me mail through the contact page if somehow you cannot contact me with the ways mentioned above.
